# Generated by Django 4.0.10 on 2023-04-19 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 11, 26, 12, 90102)),
        ),
    ]
