# Generated by Django 4.0.10 on 2023-04-19 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_publish_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 11, 35, 20, 399347)),
        ),
    ]
